# Generated by Django 4.2.5 on 2023-09-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_assistant', '0002_rename_user_companyspecific_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificPracticeWeightRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reason', models.TextField(blank=True, max_length=500, null=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company_assistant.processpractice')),
                ('specific', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company_assistant.specific')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecificProcessRelation',
        ),
    ]
