name: Test and ZAP

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Django unit tests
      run: |
        python app/manage.py test

  zap:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: main
       - name: Building Docker Node-Goat Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach

       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.9.0
         with:
           # Target URL
           target: "http://localhost:8000/admin"
           fail_action: false
           docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
           token: ${{ secrets.GITHUB_TOKEN }}
           issue_title: Security Tests
           rules_file_name: '.zap/rules.tsv'
